In [1]:
import pandas as pd
import random as random

In [2]:
def get_magic_item_prices_df(discount_rate=0):
    """Get a pandas DataFrame of randomized magic item prices based on their rarity and a given discount rate."""
    rarity_prices = {
        "common": (50, 100, 1),
        "uncommon": (101, 500, 1),
        "rare": (501, 5_000, 6),
        "very rare": (5_001, 50_000, 11),
        "legendary": (50_001, 500_000, 17)
    }
    prices = []
    for rarity in rarity_prices:
        price_range = rarity_prices[rarity][:2]
        original_price = random.randint(price_range[0], price_range[1])
        discounted_price = int(original_price * (1 - discount_rate))
        difference = original_price - discounted_price
        level = rarity_prices[rarity][2]
        prices.append([rarity, original_price, discounted_price, difference, level])
    df = pd.DataFrame(prices, columns=["Rarity", "Original Price (gold pieces)", "Discounted Price (gold pieces)", "Discount (gold pieces)", "Minimum Character Level"])
    df["Discount Rate"] = f"{discount_rate * 100}%"
    return df

# My HomeBrew Magic Items

## Prices by rarity

Rarity  | Price Range
--------|------------
Common  | 50-100 gp
Uncommon| 101-500 gp
Rare    | 501-5,000 gp
Very Rare | 5,001-50,000 gp
Legendary | 50,001+ gp

## Common

50-100gp

- [Spear of Steadfast Faith](https://www.dndbeyond.com/magic-items/6563063-spear-of-steadfast-faith) Cleric
- [Ki Crystal Pendant](https://www.dndbeyond.com/magic-items/6630312-ki-crystal-pendant) Monk
- [Gnomish Multiplexer](https://www.dndbeyond.com/magic-items/6563150-gnomish-multiplexer) Artificer
- [Chaotic Control Band](https://www.dndbeyond.com/magic-items/6563102-chaotic-control-band) Sorcerer (Wild Magic)
- [Ironclad Boots](https://www.dndbeyond.com/magic-items/6630248-ironclad-boots) Fighter

## Uncommon

101-500gp

## Rare 

501-5,000gp

- [Spear of Spiritual Radiance](https://www.dndbeyond.com/magic-items/6569254-spear-of-spiritual-radiance) Cleric

## Very Rare

5,001-50,000gp

## Legendary

50,000gp

In [4]:
# Example usage
discount_rate = 0.2
prices_df = get_magic_item_prices_df(discount_rate)
prices_df

,Rarity,Original Price (gold pieces),Discounted Price (gold pieces),Discount (gold pieces),Minimum Character Level,Discount Rate
0,common,77,61,16,1,20.0%
1,uncommon,236,188,48,1,20.0%
2,rare,4305,3444,861,6,20.0%
3,very rare,10832,8665,2167,11,20.0%
4,legendary,217307,173845,43462,17,20.0%